In [3]:
 import numpy as np

In [4]:
A = np.array([1,2,6])
A.shape

(3,)

In [5]:
B = np.zeros((3,2))  #contructeur avec de zeros
B


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
B.shape

(3, 2)

In [7]:
C = np.ones((3,5))
C

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
C.size    #indique la taille

15

In [9]:
d = np.full((2,5), 9)
d

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [10]:
np.random.randn(3,4)   #génères les nombre aléatoire issue de la distribution normale centré en 0

array([[-1.86920394, -0.16257522, -2.1599501 ,  0.41650114],
       [-0.33855133,  0.06542659,  0.32167712, -0.44001166],
       [-0.5459552 , -1.55696587,  0.13086654,  0.83227079]])

In [11]:
np.random.seed(0)
np.random.randn(3,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [12]:
np.eye(5)    # réation d'une matrice identité 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.linspace(0,10, 20)    #debut,fin, nombre des points

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [14]:
np.arange(0, 10, 0.5)    #début,fin, les pas

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [15]:
np.linspace(0,10, 20, dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

#MANIPULATION 

In [16]:
A = np.zeros((3, 2))
B = np.ones((3, 2))

In [17]:
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [18]:
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
np.hstack((A, B))

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [20]:
np.vstack((A, B))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
np.concatenate((A, B), axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [22]:
np.concatenate((A, B), axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
D = np.concatenate((A, B), axis=0)
D.shape

(6, 2)

In [24]:
D.size

12

In [25]:
D = D.reshape((3,4))    #changer des formes
D

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
A = np.array([1, 2, 3])
A = A.reshape((3,1))
A.shape

(3, 1)

In [27]:
A = np.array([1, 2, 3])
A = A.reshape((A.shape[0],1))
A.shape

(3, 1)

In [28]:
A = A.squeeze()
A.shape

(3,)

In [29]:
D.ravel()

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])

In [30]:
D.ravel().shape

(12,)

In [31]:
#EXERCICE

In [33]:
def initialisations(m,n):
    np.random.seed(0)
    E_1 = np.random.randint(0, 10, [m,n+1])
    E_2 = np.ones((m,1))
    E = np.concatenate((E_1, E_2), axis=1)
    return E

print(initialisations(4,3))
    

[[5. 0. 3. 3. 1.]
 [7. 9. 3. 5. 1.]
 [2. 4. 7. 6. 1.]
 [8. 8. 1. 6. 1.]]
