In [1]:
import numpy as np

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
A[1, 0]   

np.int64(4)

###indexing

In [23]:
print(A[:, 0])

[1 4 7]


In [24]:
print(A[0, :])

[1 2 3]


In [25]:
print(A[2])

[7 8 9]


In [26]:
#bloc

In [32]:
A[0:2, 0:2] = 10
A


array([[10, 10,  3],
       [10, 10,  6],
       [ 7,  8,  9]])

In [35]:
print(A[0:3, 1:3])


[[10  3]
 [10  6]
 [ 8  9]]


In [36]:
B = np.zeros((4, 4))
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
B[1:3, 1:3] = 1
B

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [38]:
c = np.zeros((5, 5))
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
c[0:5:2, 0:5:2] = 1
c

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])

### Technique du boolean indexing

In [45]:
A = np.random.randint(0,10 , [5, 5])
A

array([[6, 4, 3, 6, 6],
       [4, 6, 0, 9, 9],
       [7, 6, 1, 4, 5],
       [3, 7, 1, 3, 5],
       [1, 0, 1, 7, 5]], dtype=int32)

In [46]:
A < 5   #msque

array([[False,  True,  True, False, False],
       [ True, False,  True, False, False],
       [False, False,  True,  True, False],
       [ True, False,  True,  True, False],
       [ True,  True,  True, False, False]])

In [47]:
A[A < 5] = 10
A

array([[ 6, 10, 10,  6,  6],
       [10,  6, 10,  9,  9],
       [ 7,  6, 10, 10,  5],
       [10,  7, 10, 10,  5],
       [10, 10, 10,  7,  5]], dtype=int32)

In [48]:
A[(A < 5) & (A > 2)] = 10
A

array([[ 6, 10, 10,  6,  6],
       [10,  6, 10,  9,  9],
       [ 7,  6, 10, 10,  5],
       [10,  7, 10, 10,  5],
       [10, 10, 10,  7,  5]], dtype=int32)

In [3]:
from scipy import misc
import matplotlib.pyplot as plt
faces = misc.d
plt.imshow(faces, cmap=plt.cm.gray)
plt.show()
faces.shape

AttributeError: module 'scipy.misc' has no attribute 'face'