fonction des bases

In [1]:
x = -2
abs(x)

2

In [2]:
x = 2.12
round(x)

2

In [3]:
liste_1 = [0,22,67,-7]


In [4]:
max(liste_1)

67

In [5]:
min(liste_1)

-7

In [6]:
len(liste_1)

4

In [7]:
sum(liste_1)

82

In [8]:
liste_2 = [True,True,False]
all(liste_2)

False

In [9]:
any(liste_2)

True

fonction utiles 

In [10]:
x = 10
type(x)

int

In [11]:
x = str(x)
x
type(x)

str

In [12]:
y = '20'
y= int(y)
y

20

conversion

In [13]:
liste_1 = [0,61,62,65,567]

In [14]:
tuple(liste_1)

(0, 61, 62, 65, 567)

In [15]:
inventaire = {
    "bananes" : 5000,
    "pommes" : 2099,
    "poires" : 56898,
    "cerises" : 2892,
}


In [16]:
list(inventaire.keys())

['bananes', 'pommes', 'poires', 'cerises']

In [17]:
bin(15)

'0b1111'

In [18]:
oct(15)

'0o17'

In [19]:
hex(15)

'0xf'

Imput

In [ ]:
x = int(input('Entrez un nombre'))

In [ ]:
type(x)

int

FORMAT()

In [ ]:
x = 25
ville = 'Paris'
message = "la température est de {} degC à {}".format(x,ville)
print(message)

la température est de 25 degC à Paris


In [ ]:
import numpy as np

In [ ]:
parametres = {
    "w1" : np.random.randn(2, 4),
    "b1" : np.zeros((2, 1)),
    "w2" : np.random.randn(2, 2),
    "b2" : np.zeros((2, 1)),
}


In [ ]:
for i in range(1,3):
    print("couche",i)
    print(parametres["w{}".format(i)])

couche 1
[[-0.4431411  -0.90031437  1.8526021  -1.39769752]
 [ 0.6587883   1.4536981   0.55433211  0.98677948]]
couche 2
[[ 0.06233069 -0.06084077]
 [ 1.76495855 -0.42720036]]


OPEN


In [ ]:
f = open('fichier.txt', 'w')

In [ ]:
f.write('bonjour')
f.close()

In [ ]:
f = open('fichier.txt' , 'r')
f.read()
f.close()

In [ ]:
with open('fichier.txt' , 'r') as f:
    print(f.read())



bonjour


In [ ]:
with open('fichier.txt' , 'w') as f:
    for i in range(10):
        f.write("{}^2 = {} \n".format(i,i**2))

In [ ]:
with open('fichier.txt' , 'r') as f:
    print(f.read())


0^2 = 0 
1^2 = 1 
2^2 = 4 
3^2 = 9 
4^2 = 16 
5^2 = 25 
6^2 = 36 
7^2 = 49 
8^2 = 64 
9^2 = 81 

