fonction des bases

In [87]:
x = -2
abs(x)

2

In [88]:
x = 2.12
round(x)

2

In [89]:
liste_1 = [0,22,67,-7]


In [90]:
max(liste_1)

67

In [91]:
min(liste_1)

-7

In [92]:
len(liste_1)

4

In [93]:
sum(liste_1)

82

In [94]:
liste_2 = [True,True,False]
all(liste_2)

False

In [95]:
any(liste_2)

True

fonction utiles 

In [96]:
x = 10
type(x)

int

In [97]:
x = str(x)
x
type(x)

str

In [98]:
y = '20'
y= int(y)
y

20

conversion

In [99]:
liste_1 = [0,61,62,65,567]

In [100]:
tuple(liste_1)

(0, 61, 62, 65, 567)

In [101]:
inventaire = {
    "bananes" : 5000,
    "pommes" : 2099,
    "poires" : 56898,
    "cerises" : 2892,
}


In [102]:
list(inventaire.keys())

['bananes', 'pommes', 'poires', 'cerises']

In [103]:
bin(15)

'0b1111'

In [104]:
oct(15)

'0o17'

In [105]:
hex(15)

'0xf'

Imput

In [106]:
x = int(input('Entrez un nombre'))

In [107]:
type(x)

int

FORMAT()

In [108]:
x = 25
ville = 'Paris'
message = "la température est de {} degC à {}".format(x,ville)
print(message)

la température est de 25 degC à Paris


In [109]:
import numpy as np

In [110]:
parametres = {
    "w1" : np.random.randn(2, 4),
    "b1" : np.zeros((2, 1)),
    "w2" : np.random.randn(2, 2),
    "b2" : np.zeros((2, 1)),
}


In [111]:
for i in range(1,3):
    print("couche",i)
    print(parametres["w{}".format(i)])

couche 1
[[ 1.27829766 -1.65001648 -1.04897051 -1.11583732]
 [ 0.22017242 -1.24302304 -0.47087928  1.19475196]]
couche 2
[[1.03681065 0.01376721]
 [0.57288807 1.11374647]]


OPEN


In [112]:
f = open('fichier.txt', 'w')

In [113]:
f.write('bonjour')
f.close()

In [114]:
f = open('fichier.txt' , 'r')
f.read()
f.close()

In [115]:
with open('fichier.txt' , 'r') as f:
    print(f.read())



bonjour


In [116]:
with open('fichier.txt' , 'w') as f:
    for i in range(10):
        f.write("{}^2 = {} \n".format(i,i**2))

In [117]:
with open('fichier.txt' , 'r') as f:
    print(f.read())


0^2 = 0 
1^2 = 1 
2^2 = 4 
3^2 = 9 
4^2 = 16 
5^2 = 25 
6^2 = 36 
7^2 = 49 
8^2 = 64 
9^2 = 81 



In [ ]:
V = ['BAMPIRE', 'ETIENNE', 'MALIKA', 'YASSINE', 'FATIMA']

any(V)

True

In [119]:
t = 12
i = 2
result = f'le resultat est {t}volts et {i}ampères'
