In [188]:
import numpy as np
import os as o
import math as m
import sympy as sp


In [189]:
A = np.array([1,2,6])
A.shape

(3,)

In [190]:
A_x = np.array([[2, -2, 4], [0, 2, 3], [1, 6, 2]])
print(A_x)
A_x.shape



[[ 2 -2  4]
 [ 0  2  3]
 [ 1  6  2]]


(3, 3)

In [191]:
B = np.zeros((3,2))  #contructeur avec de zeros
B


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [192]:
V = np.zeros((10,10))
V


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [193]:
B.shape

(3, 2)

In [194]:
C = np.ones((3,5))
C

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [195]:
W = np.ones((10,10))
W


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [196]:

W = W*(-6)

W

array([[-6., -6., -6., -6., -6., -6., -6., -6., -6., -6.],
       [-6., -6., -6., -6., -6., -6., -6., -6., -6., -6.],
       [-6., -6., -6., -6., -6., -6., -6., -6., -6., -6.],
       [-6., -6., -6., -6., -6., -6., -6., -6., -6., -6.],
       [-6., -6., -6., -6., -6., -6., -6., -6., -6., -6.],
       [-6., -6., -6., -6., -6., -6., -6., -6., -6., -6.],
       [-6., -6., -6., -6., -6., -6., -6., -6., -6., -6.],
       [-6., -6., -6., -6., -6., -6., -6., -6., -6., -6.],
       [-6., -6., -6., -6., -6., -6., -6., -6., -6., -6.],
       [-6., -6., -6., -6., -6., -6., -6., -6., -6., -6.]])

In [197]:
C.size    #indique la taille

15

In [198]:
W
W**4

array([[1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296.,
        1296.],
       [1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296.,
        1296.],
       [1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296.,
        1296.],
       [1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296.,
        1296.],
       [1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296.,
        1296.],
       [1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296.,
        1296.],
       [1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296.,
        1296.],
       [1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296.,
        1296.],
       [1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296.,
        1296.],
       [1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296., 1296.,
        1296.]])

In [223]:
np.full((5,5), 2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [199]:
d = np.full((2,5), 9)
d

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [225]:
np.full((5,5), 'B')

array([['B', 'B', 'B', 'B', 'B'],
       ['B', 'B', 'B', 'B', 'B'],
       ['B', 'B', 'B', 'B', 'B'],
       ['B', 'B', 'B', 'B', 'B'],
       ['B', 'B', 'B', 'B', 'B']], dtype='<U1')

In [200]:
np.random.randn(3,4)   #génères les nombre aléatoire issue de la distribution normale centré en 0

array([[-0.08767307,  1.36687937,  1.1253141 , -0.35899555],
       [ 1.2206081 , -1.33949555,  0.42837337, -0.12346315],
       [ 1.41437719, -0.12405066,  2.00815709,  0.22988654]])

In [226]:
import random


In [ ]:
z = random.randrange(-6,6)
print(z)

3


In [242]:
np.random.seed(0)
np.random.randn(3,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [202]:
np.eye(5)    # création d'une matrice identité 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(0,10, 20)    #debut,fin, nombre des points

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [245]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [248]:
np.arange(-10, -1, 1)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2])

In [204]:
np.arange(0, 10, 0.5)    #début,fin, les pas

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [205]:
np.linspace(0,10, 20, dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

#MANIPULATION 

In [206]:
A = np.zeros((3, 2))
B = np.ones((3, 2))

In [207]:
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [208]:
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [209]:
np.hstack((A, B))

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [210]:
np.vstack((A, B))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [211]:
np.concatenate((A, B), axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [212]:
np.concatenate((A, B), axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [213]:
D = np.concatenate((A, B), axis=0)
D.shape

(6, 2)

In [214]:
D.size

12

In [215]:
D = D.reshape((3,4))    #changer des formes
D

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [216]:
A = np.array([1, 2, 3])
A = A.reshape((3,1))
A.shape

(3, 1)

In [217]:
A = np.array([1, 2, 3])
A = A.reshape((A.shape[0],1))

A.shape

(3, 1)

In [218]:
A = A.squeeze() 
A.shape


(3,)

In [219]:
D.ravel() 

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])

In [220]:
D.ravel().shape

(12,)

In [251]:
np.random.randint(-5, 5,[6, 5])

array([[-3, -5, -5, -1,  0],
       [ 0,  1,  3, -1, -4],
       [-1,  4,  3, -4, -4],
       [ 2,  4,  4, -2,  1],
       [ 2, -3, -5, -2,  0],
       [ 4, -1, -1,  1, -1]], dtype=int32)

In [221]:
#EXERCICE

In [222]:
def initialisations(m,n):
    np.random.seed(0)
    E_1 = np.random.randint(0, 10, [m,n+1])
    E_2 = np.ones((m,1))
    E = np.concatenate((E_1, E_2), axis=1)
    return E

print(initialisations(4,3))
# explication : la fonction initialisations génère une matrice de taille m x (n+1) avec des nombres aléatoires entre 0 et 9, puis ajoute une colonne de 1 à la fin de cette matrice.
    

[[5. 0. 3. 3. 1.]
 [7. 9. 3. 5. 1.]
 [2. 4. 7. 6. 1.]
 [8. 8. 1. 6. 1.]]
