In [2]:
import numpy as np

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
A[1, 0]   

np.int64(4)

###indexing

In [5]:
print(A[:, 0])

[1 4 7]


In [6]:
print(A[0, :])

[1 2 3]


In [7]:
print(A[2])

[7 8 9]


In [8]:
#bloc

In [9]:
A[0:2, 0:2] = 10
A


array([[10, 10,  3],
       [10, 10,  6],
       [ 7,  8,  9]])

In [10]:
print(A[0:3, 1:3])


[[10  3]
 [10  6]
 [ 8  9]]


In [11]:
B = np.zeros((4, 4))
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
B[1:3, 1:3] = 1
B

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [13]:
c = np.zeros((5, 5))
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
c[0:5:2, 0:5:2] = 1
c

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])

### Technique du boolean indexing

In [15]:
A = np.random.randint(0,10 , [5, 5])
A

array([[4, 8, 6, 3, 9],
       [6, 5, 7, 5, 4],
       [1, 4, 5, 0, 3],
       [5, 7, 4, 2, 1],
       [7, 8, 0, 9, 1]], dtype=int32)

In [16]:
A < 5   #msque

array([[ True, False, False,  True, False],
       [False, False, False, False,  True],
       [ True,  True, False,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True, False,  True]])

In [17]:
A[A < 5] = 10
A

array([[10,  8,  6, 10,  9],
       [ 6,  5,  7,  5, 10],
       [10, 10,  5, 10, 10],
       [ 5,  7, 10, 10, 10],
       [ 7,  8, 10,  9, 10]], dtype=int32)

In [18]:
A[(A < 5) & (A > 2)] = 10
A

array([[10,  8,  6, 10,  9],
       [ 6,  5,  7,  5, 10],
       [10, 10,  5, 10, 10],
       [ 5,  7, 10, 10, 10],
       [ 7,  8, 10,  9, 10]], dtype=int32)

In [19]:
from scipy import misc
import matplotlib.pyplot as plt
faces = misc.d
plt.imshow(faces, cmap=plt.cm.gray)
plt.show()
faces.shape

AttributeError: module 'scipy.misc' has no attribute 'd'