In [3]:
import numpy as np

In [ ]:
np.random.seed(0)
A = np.random.randint(0, 10,[5, 5])
A
                      

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]], dtype=int32)

In [17]:
np.random.seed(50)
B = np.random.randint(-1,1,[10,15])
B
#help(np.random)


array([[-1, -1,  0,  0,  0, -1, -1, -1,  0, -1, -1,  0,  0, -1,  0],
       [-1,  0,  0, -1, -1,  0, -1,  0, -1, -1, -1, -1,  0,  0,  0],
       [ 0, -1,  0, -1, -1,  0, -1,  0, -1,  0, -1,  0,  0,  0, -1],
       [-1,  0, -1, -1, -1,  0, -1, -1, -1, -1,  0, -1,  0,  0, -1],
       [-1,  0, -1, -1,  0,  0, -1, -1,  0, -1, -1,  0,  0, -1, -1],
       [-1, -1,  0, -1,  0,  0, -1,  0,  0,  0,  0,  0,  0, -1,  0],
       [ 0,  0, -1,  0,  0,  0,  0, -1, -1,  0, -1, -1, -1, -1,  0],
       [-1, -1, -1,  0,  0, -1,  0, -1, -1, -1, -1,  0,  0, -1,  0],
       [-1, -1, -1, -1,  0, -1,  0,  0, -1, -1,  0,  0, -1,  0, -1],
       [-1, -1,  0, -1,  0, -1, -1, -1,  0,  0,  0,  0,  0,  0,  0]],
      dtype=int32)

### METHODES NDARRAY

In [3]:
A.sum(axis = 1)

array([18, 23, 30, 29, 35])

In [4]:
A.sum(axis = 0)

array([32, 25, 31, 30, 17])

In [18]:
A.cumsum(axis =0) #somme cumulée

array([[ 5,  0,  3,  3,  7],
       [14,  3,  8,  5, 11],
       [21,  9, 16, 13, 12],
       [27, 16, 23, 21, 13],
       [32, 25, 31, 30, 17]])

In [19]:
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]], dtype=int32)

In [20]:
A.cumsum(axis = 1)

array([[ 5,  5,  8, 11, 18],
       [ 9, 12, 17, 19, 23],
       [ 7, 13, 21, 29, 30],
       [ 6, 13, 20, 28, 29],
       [ 5, 14, 22, 31, 35]])

In [22]:
A.min(axis=1)

array([0, 2, 1, 1, 4], dtype=int32)

In [6]:
A.min(axis =0)

array([5, 0, 3, 2, 1], dtype=int32)

In [7]:
A.argmin(axis = 0)   ##Trouver la position du minimum

array([0, 0, 0, 1, 2])

In [23]:
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]], dtype=int32)

In [25]:
A.argsort()
help(np.argsort)

Help on _ArrayFunctionDispatcher in module numpy:

argsort(a, axis=-1, kind=None, order=None, *, stable=None)
    Returns the indices that would sort an array.

    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.

    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort under the covers and, in general, the
        actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    order : str or list of str, optional
    

In [9]:
np.exp(A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01, 2.00855369e+01,
        1.09663316e+03],
       [8.10308393e+03, 2.00855369e+01, 1.48413159e+02, 7.38905610e+00,
        5.45981500e+01],
       [1.09663316e+03, 4.03428793e+02, 2.98095799e+03, 2.98095799e+03,
        2.71828183e+00],
       [4.03428793e+02, 1.09663316e+03, 1.09663316e+03, 2.98095799e+03,
        2.71828183e+00],
       [1.48413159e+02, 8.10308393e+03, 2.98095799e+03, 8.10308393e+03,
        5.45981500e+01]])

###statistique

In [27]:
A.mean()    #lamoyenne

np.float64(5.4)

In [11]:
A.std()  #ecart type

np.float64(2.6683328128252666)

In [12]:
A.var()  #la variance

np.float64(7.12)

In [13]:
np.corrcoef(A)   #matrix de correleration

array([[ 1.        ,  0.39741307, -0.59190035, -0.77390599, -0.89934617],
       [ 0.39741307,  1.        ,  0.09521171, -0.11337365, -0.59181844],
       [-0.59190035,  0.09521171,  1.        ,  0.9579589 ,  0.6947088 ],
       [-0.77390599, -0.11337365,  0.9579589 ,  1.        ,  0.84515425],
       [-0.89934617, -0.59181844,  0.6947088 ,  0.84515425,  1.        ]])

In [14]:
np.corrcoef(A)[0, 1] 

np.float64(0.39741306906256163)

In [15]:
np.unique(A, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3]))

In [16]:
values, counts = np.unique(A, return_counts=True)

In [17]:
counts

array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3])

In [18]:
counts.argsort()

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8])

In [19]:
values[counts.argsort()]

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8], dtype=int32)

In [37]:
student = ["Jenovie","etienne","lucie", "David"]
student[0]
student[-1]

for i,j in enumerate(student):
    print(i, ". NOM : ",j)
    
age = [20, 22, 22,22]
age

for i,j in zip(age,student):
    print("AGe:",i,j)

0 . NOM :  Jenovie
1 . NOM :  etienne
2 . NOM :  lucie
3 . NOM :  David
AGe: 20 Jenovie
AGe: 22 etienne
AGe: 22 lucie
AGe: 22 David


In [20]:
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'valeur {i} apprait {j}')


valeur 0 apprait 1
valeur 2 apprait 1
valeur 1 apprait 2
valeur 4 apprait 2
valeur 6 apprait 2
valeur 3 apprait 3
valeur 5 apprait 3
valeur 9 apprait 3
valeur 7 apprait 4
valeur 8 apprait 4


In [21]:
### NAN CORRECTIONS

In [22]:
np.random.seed(0)
B = np.random.randn(5, 5)
B[0, 2] = np.nan
B[4, 3] = np.nan
B

array([[ 1.76405235,  0.40015721,         nan,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ,         nan,  2.26975462]])

In [23]:
np.nanstd(B)

np.float64(1.0820969161820175)

In [24]:
np.isnan(B)

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [25]:
np.isnan(B).sum()

np.int64(2)

In [26]:
np.isnan(B).sum()/B.size

np.float64(0.08)

In [27]:
np.isnan(B)

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [28]:
B[np.isnan(B)] = 0
B

array([[ 1.76405235,  0.40015721,  0.        ,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ,  0.        ,  2.26975462]])

ALGEBRE LINEAIRE

In [29]:
A = np.ones((2, 3))
B = np.ones((3, 2))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
A.T    #Transposition 

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
A.dot(B)    #produits de matrix

array([[3., 3.],
       [3., 3.]])

In [33]:
B.dot(A)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [34]:
A = np.random.randint(0, 10, [3, 3])
A

array([[0, 4, 5],
       [5, 6, 8],
       [4, 1, 4]], dtype=int32)

In [35]:
np.linalg.det(A)    #calcul du determinant

np.float64(-46.99999999999999)

In [36]:
np.linalg.inv(A)

array([[-0.34042553,  0.23404255, -0.04255319],
       [-0.25531915,  0.42553191, -0.53191489],
       [ 0.40425532, -0.34042553,  0.42553191]])

In [37]:
np.linalg.pinv(A)

array([[-0.34042553,  0.23404255, -0.04255319],
       [-0.25531915,  0.42553191, -0.53191489],
       [ 0.40425532, -0.34042553,  0.42553191]])

In [38]:
np.linalg.eig(A)    #valeur propres et vecteur propre

EigResult(eigenvalues=array([11.70711161, -3.03144729,  1.32433567]), eigenvectors=array([[-0.42874248, -0.87114314, -0.19148208],
       [-0.84038624,  0.04955314, -0.79053568],
       [-0.33155821,  0.48852239,  0.58171123]]))

In [39]:
np.random.seed(0)
A = np.random.randint(0,100, [10, 5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]], dtype=int32)

In [40]:
A.mean(axis= 0)

array([44.5, 47. , 60.5, 45.7, 64.5])

In [41]:
A.std(axis = 0)

array([22.66384786, 22.28003591, 26.5678377 , 29.36341261, 23.2432786 ])

In [42]:
D = (A -A.mean(axis= 0)) / A.std(axis = 0)

In [43]:
print(D)

[[-0.02206157  0.          0.13173823  0.72539252  0.10755798]
 [-1.56637126  1.61579632 -1.48676006 -0.33034307  0.96802178]
 [ 1.12513992  1.84021247  1.03508612 -1.14768676 -0.27965074]
 [ 0.90452425 -0.35906585  0.99744662  0.0102168   1.01104497]
 [ 1.6104944  -0.44883231 -1.33620208  1.0659524   0.32267393]
 [-1.56637126 -1.21184724  0.73397016  0.7935045   0.62383626]
 [ 0.11030784  0.76301493  0.80924915  1.81518411  1.01104497]
 [ 0.1985541  -0.80789816 -1.56203905 -0.90929485 -2.17267111]
 [-0.24267724 -0.67324847  0.16937773 -1.24985473 -0.32267393]
 [-0.55153918 -0.7181317   0.50813319 -0.77307091 -1.26918412]]


In [44]:
D.std(axis = 0)

array([1., 1., 1., 1., 1.])

### 