In [1]:
import numpy as np

In [2]:
np.random.seed(0)
A = np.random.randint(0, 10, [4,1])
B = np.ones((1, 3))

# le broadcasting de A et B   c'est comme si on avait fait :
# A = np.array([[0], [1], [2], [3]])
# B = np.array([[1, 1, 1]])
# C = A + B
C = A + B
print(C)

[[6. 6. 6.]
 [1. 1. 1.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [3]:
A 

array([[5],
       [0],
       [3],
       [3]], dtype=int32)

In [4]:
B

array([[1., 1., 1.]])

In [5]:
print(A + B)

[[6. 6. 6.]
 [1. 1. 1.]
 [4. 4. 4.]
 [4. 4. 4.]]
