In [43]:
#----------------  02   IMPUTER            remplacer les données manquante  ------------------

In [44]:
import numpy as np # pour les calculs numériques
import matplotlib.pyplot as plt # pour la visualisation
import pandas as pd # pour la manipulation de données
import seaborn as sns # pour la visualisation de données
from sklearn.linear_model import SGDClassifier # pour la classification linéaire

In [45]:
#--------------   SIMPLE  IMPUTER 

"""
ce quoi l'imputation ?
l'imputation est une technique qui permet de remplacer les données manquantes par des valeurs estimées à partir des données disponibles.
il existe plusieurs méthodes d'imputation, mais la plus simple est l'imputation par la moyenne, la médiane ou la valeur la plus fréquente (mode)
 pour les données numériques, et la valeur la plus fréquente pour les données catégorielles.
"""

"\nce quoi l'imputation ?\nl'imputation est une technique qui permet de remplacer les données manquantes par des valeurs estimées à partir des données disponibles.\nil existe plusieurs méthodes d'imputation, mais la plus simple est l'imputation par la moyenne, la médiane ou la valeur la plus fréquente (mode)\n pour les données numériques, et la valeur la plus fréquente pour les données catégorielles.\n"

In [46]:
from sklearn.impute import SimpleImputer # pour l'imputation simple des données manquantes

In [47]:
x = np.array([[10, 3],
             [0, 4],
             [5, 3],
             [np.nan, 3]])
# ce code crée un tableau numpy avec des données numériques, où la dernière ligne contient une valeur manquante (np.nan)
imputer = SimpleImputer(strategy='mean') # on crée un objet imputer avec la stratégie d'imputation par la moyenne
x_imputed = imputer.fit_transform(x) # on applique l'imputation sur le tableau x et on stocke le résultat dans x_imputed
print(x_imputed) # on affiche le tableau imputé, où la valeur manquante a été remplacée par la moyenne des autres valeurs de la colonne (5.0 dans ce cas)   

[[10.  3.]
 [ 0.  4.]
 [ 5.  3.]
 [ 5.  3.]]


In [48]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# ici on crée un objet imputer avec la stratégie d'imputation par la moyenne et en spécifiant que les valeurs manquantes sont représentées par np.nan


imputer.fit_transform(x)
# ici on applique l'imputation sur le tableau x et on retourne le résultat, où la valeur manquante a été remplacée par la moyenne des autres valeurs de la colonne (5.0 dans ce cas)

array([[10.,  3.],
       [ 0.,  4.],
       [ 5.,  3.],
       [ 5.,  3.]])

In [49]:
x_test = np.array([[12, 5],
                   [40, 2],
                   [5,  5],
                   [np.nan, np.nan]])

imputer.transform(x_test)
# ici on applique l'imputation sur le tableau x_test en utilisant les statistiques calculées à partir du tableau x, et on retourne le résultat, où les valeurs manquantes ont été remplacées par la moyenne des autres valeurs de chaque colonne (5.0 pour la première colonne et 3.0 pour la deuxième colonne dans ce cas)

array([[12.  ,  5.  ],
       [40.  ,  2.  ],
       [ 5.  ,  5.  ],
       [ 5.  ,  3.25]])

In [50]:
##---------    KKNImputer
# le KNNImputer est une technique d'imputation qui utilise les k plus proches voisins pour estimer les valeurs manquantes.
# il est basé sur l'idée que les données similaires ont des valeurs similaires, et il utilise les distances entre les points
#  de données pour trouver les voisins les plus proches.

In [51]:
from sklearn.impute import KNNImputer

In [52]:
x = np.array([[10, 100],
             [2, 30],
             [3, 15],
             [np.nan, 3]])

In [53]:
imputer = KNNImputer(n_neighbors=1)
imputer.fit_transform(x)

array([[ 10., 100.],
       [  2.,  30.],
       [  3.,  15.],
       [  3.,   3.]])

In [54]:
from sklearn.impute import MissingIndicator

In [55]:
x = np.array([[10, 100],
             [2, 30],
             [3, 15],
             [np.nan, np.nan]])

In [56]:
MissingIndicator().fit_transform(x)

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True]])

In [57]:
from sklearn.pipeline import make_union

In [58]:
pipeline = make_union(SimpleImputer(strategy='constant', fill_value=-99),
                      MissingIndicator())

pipeline.fit_transform(x)

array([[ 10., 100.,   0.,   0.],
       [  2.,  30.,   0.,   0.],
       [  3.,  15.,   0.,   0.],
       [-99., -99.,   1.,   1.]])

In [59]:
#-----------   APPLICATION ----------

In [60]:
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import SGDClassifier
import seaborn as sns 
from sklearn.model_selection import train_test_split

In [61]:
titanic = pd.read_csv('../datasets/titanic.csv')
# on charge le dataset titanic à partir d'un fichier CSV situé dans le dossier ../datasets/

titanic.head()
# on affiche les 5 premières lignes du dataset titanic pour avoir un aperçu des données

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [62]:
x = titanic[['pclass', 'age']]
# on sélectionne les colonnes 'pclass' et 'age' du dataset titanic pour les utiliser comme variables explicatives (features) dans notre modèle de classification

y= titanic['survived']


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 5)
# on divise les données en un ensemble d'entraînement (x_train, y_train) et 
# un ensemble de test (x_test, y_test) en utilisant la 
# fonction train_test_split de scikit-learn, avec une taille de test de 20% 
# et une graine aléatoire de 5 pour assurer la reproductibilité des résultats

In [63]:
model = make_pipeline( KNNImputer(), SGDClassifier())

In [64]:
params = {
    'knnimputer__n_neighbors' : [1, 2, 3, 4] 
}
# ici on définit les paramètres à tester pour le KNNImputer, en 
# spécifiant les différentes valeurs de n_neighbors à essayer (1, 2, 3 et 4)

In [65]:
grid = GridSearchCV(model, param_grid=params, cv =5)
# ici on crée un objet GridSearchCV pour effectuer une recherche en grille 
# sur les paramètres du modèle, en utilisant une validation croisée à 5 plis (cv=5)

In [66]:
grid
# ici on affiche l'objet GridSearchCV pour voir les paramètres et les options de validation croisée qui ont été définis

,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",Pipeline(step...lassifier())])
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'knnimputer__n_neighbors': [1, 2, ...]}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion ` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",None
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",None
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- An iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide ` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",5
,"verbose verbose: intControls the verbosity: the higher, the more messages.- >1 : the computation time for each fold and parameter candidate is displayed;- >2 : the score is also displayed;- >3 : the fold and ca

In [67]:
grid.fit(x_train,y_train)
# ici on entraîne le modèle en utilisant la méthode fit de GridSearchCV, qui effectue la recherche en grille sur les paramètres spécifiés et évalue les performances du modèle à l'aide de la validation croisée, en utilisant les données d'entraînement (x_train, y_train)


,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",Pipeline(step...lassifier())])
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'knnimputer__n_neighbors': [1, 2, ...]}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion ` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",None
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",None
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- An iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide ` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",5
,"verbose verbose: intControls the verbosity: the higher, the more messages.- >1 : the computation time for each fold and parameter candidate is displayed;- >2 : the score is also displayed;- >3 : the fold and ca

In [68]:
grid.best_params_
# ici on affiche les meilleurs paramètres trouvés par la recherche en grille,
#  qui sont les valeurs de n_neighbors qui ont donné les meilleures performances 
# lors de la validation croisée

{'knnimputer__n_neighbors': 1}